### ISSUE TITLE
raistlin init

### ISSUE THREAD

**Issue by asbjornenge** [asbjornenge/raistlin#1]
Make it easy to create new raistlin apps. Include a appropriate package.json etc.

**Comment by asbjornenge** [comment]
@educastellano - maybe the `raistlin-cli` should be a separate module? What do you think?

**Comment by asbjornenge** [comment]
Well, raistlin is already a cli, so it probably does not make sense :see_no_evil: :horse:

**Comment by educastellano** [comment]
yeah, just another sub-command of this package I think :)

**Comment by asbjornenge** [comment]
I did that :+1:
